package main

import "Projects/calculator"

func main(){
 calculator.Addint8()
 calculator.Addint16()
 calculator.Addint32()
 calculator.Addint64()	
 calculator.Adduint8()
 calculator.Adduint16()	
 calculator.Adduint32()
 calculator.Adduint64()
 calculator.Addfloat32()
 calculator.Addfloat64()	
 calculator.Multiplyint8()
 calculator.Multiplyint16()
 calculator.Multiplyint32()
 calculator.Multiplyint64()
 calculator.Multiplyuint8()
 calculator.Multiplyuint16()
 calculator.Multiplyuint32()
 calculator.Multiplyint64()
 calculator.Multiplyfloat32()
 calculator.Multiplyfloat64()
 calculator.Subtractint8()
 calculator.Subtractint16()
 calculator.Subtractint32()
 calculator.Subtractint64()
 calculator.Subtractuint8()
 calculator.Subtractuint16()
 calculator.Subtractuint32()
 calculator.Subtractuint64()
 calculator.Subtractfloat32()
 calculator.Subtractfloat64()
 calculator.Divideint8()
 calculator.Divideint16()
 calculator.Divideint32()
 calculator.Divideint64()
 calculator.Divideuint8()
 calculator.Divideuint16() 
 calculator.Divideuint32() 
 calculator.Divideuint64() 
 calculator.Dividefloat32() 
 calculator.Dividefloat64() 
}